services:
  helloworld:
    build: ./docker_compose_web
    ports:
      - "8098:5000"

  nginx:
    image: nginx
    ports:
      - "80:80"

  client:
    build: ./client
    depends_on:
      - helloworld
